version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - pgnetwork
    
  server:
    build: ./server/
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
    networks:
      - pgnetwork
    links:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - pgnetwork
    links:
      - db

volumes:
  db:
    driver: local

networks:
  pgnetwork:
    driver: bridge